import type { Metadata } from "next";
import { Inter, JetBrains_Mono, League_Gothic, Montserrat } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["700"], // Bold 700
});


const leagueGothic = League_Gothic({
  variable: "--font-league-gothic",
  subsets: ["latin"],
  weight: "400", // League Gothic only has 400
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainMono.variable} ${montserrat.variable} ${leagueGothic.variable}`}>
      <body className="font-sans">
        {/* <Navbar /> */}
        <main>
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
